- hosts: localhost
  gather_facts: false

  tasks:
    - name: Get epoch value of current time
      set_fact:
        time_start: "{{ lookup('pipe', 'date +%s') }}"

    - name: Get epoch value of future time point
      set_fact:
        time_start_plus_1min: "{{ (time_start | int) + 60*1 }}"

    - name: Print now and future epoch time
      debug:
        msg: 
          - "time start : {{ time_start }}"
          - "future time: {{ time_start_plus_1min }}"

    - name: Print now and future formatted time
      debug:
        msg: 
          - "time start : {{ '%Y-%m-%d %H:%M:%S' | strftime(time_start) }}"
          - "future time: {{ '%Y-%m-%d %H:%M:%S' | strftime(time_start_plus_1min) }}"

    - name: Wait for time point 
      shell: date +%s
      register: current_time
      until: (current_time.stdout | int) > (time_start_plus_1min | int)
      retries: 20
      delay: 15

    - name: Run action after time point
      debug:
        msg: "Epoch time {{ time_start_plus_1min }} has passed!"
